version: '3'

services: 
    xtextjp:
        image: jekyll/jekyll
        tty: true
        volumes:
            - ../xtext-website:/srv/jekyll
        ports:
            - "4000:4000"
        entrypoint: ["bash"]